services:
  pgsql:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'wetbat-pgsql'
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
